[package]
name = "prisma-client-uniffi-generator"
version = "0.1.0"
edition = "2021"


[dependencies]
prisma-client-rust-sdk = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
