[package]
name = "prisma-client-uniffi-example-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
prisma-client-rust-cli = { workspace = true, features = [
  "sqlite",
  "migrations",
] }
prisma-client-uniffi-generator = { path = "../../generator" }