// Code generated by Example Generator. DO NOT EDIT

use crate::prisma;
impl sdk_example_lib::ExampleTrait for prisma::account::Data {
    fn scalar_fields() -> Vec<&'static str> {
        vec!["id", "display_name"]
    }
    fn relation_fields() -> Vec<&'static str> {
        vec![]
    }
    fn id_fields() -> Vec<&'static str> {
        vec!["id"]
    }
}
